# Incident and IncidentAction ORM models.
# An Incident is created when the correlation engine detects a multi-stage attack chain.
# IncidentActions record analyst actions (e.g. "blocked IP", "escalated to manager").

from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from database import Base


class Incident(Base):
    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)                        # auto-generated from attack chain + src_ip
    src_ip = Column(String, index=True)
    attack_chain = Column(Text)                   # e.g. "PortScan -> BruteForce"
    mitre_technique = Column(String)              # e.g. "T1046"
    risk_score = Column(Integer)                  # 0–100
    severity = Column(String)                     # Low / Medium / High / Critical
    status = Column(String, default="Open")       # Open / In Progress / Resolved
    assigned_to = Column(String, nullable=True)
    ai_explanation = Column(Text, nullable=True)  # generated by Gemini; null if API key absent
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    actions = relationship("IncidentAction", back_populates="incident")


class IncidentAction(Base):
    __tablename__ = "incident_actions"

    id = Column(Integer, primary_key=True, index=True)
    incident_id = Column(Integer, ForeignKey("incidents.id"))
    action = Column(String)         # free-text description of what the analyst did
    performed_by = Column(String)   # analyst username
    timestamp = Column(DateTime, default=datetime.utcnow)

    incident = relationship("Incident", back_populates="actions")
